"""add credo_activo to usuarios

Revision ID: 2634f72e93ba
Revises: 91c065a0bfc3
Create Date: 2026-05-05 19:40:40.982805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2634f72e93ba'
down_revision: Union[str, None] = '91c065a0bfc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('credo_activo', sa.Boolean(), nullable=False, server_default='true'))
    # Set existing rows to True
    op.execute("UPDATE usuarios SET credo_activo = true WHERE credo_activo IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'credo_activo')
    # ### end Alembic commands ###